version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
      # - type: volume
      #   source: dbdata
      #   target: /var/lib/postgresql/data
      #   volume:
      #     nocopy: true
    ports:
        - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
  web:
    build: .
    command: gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    ports:
        - 8000:8000

    volumes:
      # - ./:/code/
      - ./media:/code/media
      # - type: volume
      #   source: mediadata
      #   target: /code/media
      - type: bind
        source: ./static
        target: /code/static
    env_file: .env
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - ./media:/usr/share/nginx/html/media
      # - type: volume
      #   source: mediadata
      #   target: /usr/share/nginx/html/media
      - type: bind
        source: ./staticfiles
        target: /usr/share/nginx/html/static
    ports:
        - 443:80
    depends_on:
        - web    
# volumes:
#   dbdata:
#   mediadata:

