version: 2
jobs:
  deployment:
    docker:
      - image: circleci/python:3.7.4
    # working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker

      - run:
              name: Install Docker Compose
              environment:
                COMPOSE_VERSION: '1.29.2'
              command: |
                curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
                chmod +x ~/docker-compose
                sudo mv ~/docker-compose /usr/local/bin/docker-compose
      

      - run:
              name: Build images of services declared in docker-compose.yml
              command: docker-compose up -d --build
      
      - run:
          name: "setup heroku command"
          command: .circleci/scripts/setup_heroku.sh
      - run:
          name: "Heroku maintenance on"
          command: heroku maintenance:on --app ${HEROKU_APP_NAME}
      - run:
          name: "Login heroku container"
          command: "heroku container:login"
      - run:
          name: "Tag docker image"
          command: docker tag demo-docker_web registry.heroku.com/${HEROKU_APP_NAME}/web 
      - run:
          name: "Push docker image"
          command: docker push registry.heroku.com/${HEROKU_APP_NAME}/web
      # - run:
      #     name: "DB migration"
      #     command: heroku run bundle exec rails db:migrate --app ${HEROKU_APP_NAME}
      - run:
          name: "Restart app"
          command: heroku container:release web --app ${HEROKU_APP_NAME}
      - run:
          name: Heroku maintenance off
          command: heroku maintenance:off --app ${HEROKU_APP_NAME}


workflows:
  version: 2
  workflow:
    jobs:
      - deployment:
          filters:
            branches:
              only: main